name: gymnasiumEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - pip:
      - absl-py==2.1.0
      - ale-py==0.8.1
      - alembic==1.13.1
      - attrs==24.2.0
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - branca==0.7.2
      - cachetools==5.3.2
      - certifi==2023.11.17
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - colorlog==6.8.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - dataproperty==1.0.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.20.0
      - filelock==3.13.1
      - folium==0.17.0
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - greenlet==3.0.3
      - grpcio==1.60.0
      - gymnasium==0.29.1
      - huggingface-hub==0.22.0
      - huggingface-sb3==3.0
      - idna==3.6
      - importlib-resources==6.1.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - mako==1.3.2
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mbstrdecoder==1.1.3
      - mdurl==0.1.2
      - mizani==0.11.4
      - mpmath==1.3.0
      - nbformat==5.10.4
      - networkx==3.2.1
      - numpy==1.26.3
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - optuna==3.6.0
      - packaging==23.2
      - pandas==2.1.4
      - pathvalidate==3.2.0
      - patsy==0.5.6
      - pillow==10.2.0
      - pip==24.0
      - plotly==5.24.1
      - plotnine==0.13.6
      - protobuf==4.23.4
      - psutil==5.9.8
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pygame==2.5.2
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pytablewriter==1.2.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.35.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rl-zoo3==2.2.1
      - rpds-py==0.20.0
      - rsa==4.9
      - sb3-contrib==2.2.1
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.2
      - shimmy==1.3.0
      - six==1.16.0
      - sqlalchemy==2.0.29
      - stable-baselines3==2.3.0a2
      - statsmodels==0.14.3
      - sympy==1.12
      - tabledata==1.3.3
      - tcolorpy==0.1.4
      - tenacity==9.0.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.3.0
      - torch==2.1.2
      - tqdm==4.66.1
      - typepy==1.3.2
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - wasabi==1.1.2
      - werkzeug==3.0.1
      - wheel==0.38.0
      - xyzservices==2024.6.0